[build]
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions/api && npm install"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev --prefix frontend"
  targetPort = 8080
